django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django_project import views

# URLconf
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('staff/', include('staff.urls'))
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

# URLconf
urlpatterns = [
    path('', views.list, name='home'),
    path('<int:id>/', views.item, name='item')
]

staff/models.py
from django.db import models


# Create your models here.
class Gadget(models.Model):
    name = models.IntegerField()
    description = models.TextField(blank=True)
    price = models.FloatField()
    available = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}: {self.price}'

django_project/views.py
from django.http import HttpResponse


def home(request):
    return HttpResponse('Hello World')

staff/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from staff.models import Gadget


def list(request):
    gadgets = Gadget.objects.all()
    return render(request, 'staff/gadgets.html', context={'gadgets': gadgets})

def item(request, id):
    gadget = Gadget.objects.get(pk=id)
    return render(request, 'staff/gadget.html', context={'gadget': gadget})

staff/templates/staff/gadget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gadgets</title>
</head>
<body>
<a href="{% url 'staff:home' %}"><- Return</a>
<h1>{{ gadget.name }}</h1>
<h3>{{ gadget.description }}</h3>
<h3>{{ gadget.price }}</h3>

</body>
</html>

staff/templates/staff/gadgets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gadgets</title>
</head>

{% for g in gadgets %}
<a href="{% url 'staff:item' id=g.id %}">{{ g.name }}</a>
<br/>
{% endfor %}
</body>
</html>